In [28]:
a=[1,2,3,4]
[x+1 for x in a]

[2, 3, 4, 5]

In [30]:
b=[2,3,4,5]
[x+y for (x,y) in zip(a,b)]

[3, 5, 7, 9]

In [32]:
import numpy as np
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [34]:
b=np.array([2,3,4,5])
a+b

array([3, 5, 7, 9])

In [40]:
l=[0,1,2,3]
a=np.array(l)
a

array([0, 1, 2, 3])

In [42]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [44]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [52]:
np.ones(5,dtype="bool")

array([ True,  True,  True,  True,  True])

In [60]:
a=a.astype("float")
a.fill(2.5)
a

array([2.5, 2.5, 2.5, 2.5])

In [72]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a=np.linspace(1,10,21)
a

array([ 1.  ,  1.45,  1.9 ,  2.35,  2.8 ,  3.25,  3.7 ,  4.15,  4.6 ,
        5.05,  5.5 ,  5.95,  6.4 ,  6.85,  7.3 ,  7.75,  8.2 ,  8.65,
        9.1 ,  9.55, 10.  ])

In [80]:
np.random.rand(10)

array([0.39680622, 0.58285557, 0.61369784, 0.25862125, 0.18126744,
       0.62688771, 0.03968441, 0.83549705, 0.65436736, 0.92582457])

In [82]:
np.random.randn(10)

array([ 0.01481145, -1.34861356, -1.35877248, -1.02022088, -0.70820668,
       -0.2828591 ,  0.47975992,  0.35958744, -0.88191962,  0.58119595])

In [86]:
np.random.randint(1,10,10)

array([5, 4, 6, 3, 7, 5, 7, 1, 3, 2])

In [88]:
a

array([ 1.  ,  1.45,  1.9 ,  2.35,  2.8 ,  3.25,  3.7 ,  4.15,  4.6 ,
        5.05,  5.5 ,  5.95,  6.4 ,  6.85,  7.3 ,  7.75,  8.2 ,  8.65,
        9.1 ,  9.55, 10.  ])

In [90]:
type(a)

numpy.ndarray

In [96]:
a.dtype

dtype('float64')

In [98]:
a.shape

(21,)

In [102]:
np.shape(a)

(21,)

In [104]:
np.size(a)

21

In [106]:
a.size

21

In [108]:
a.ndim

1

In [116]:
a=np.array([0,1,2,3])
a[0]=1
a

array([1, 1, 2, 3])

In [118]:
a=np.array([11,12,13,14,15])
a[1:3]

array([12, 13])

In [120]:
a[1:-2]

array([12, 13])

In [122]:
a[-4:3]

array([12, 13])

In [124]:
a[-2:]

array([14, 15])

In [126]:
a[::2]

array([11, 13, 15])

In [128]:
ob=np.array([21000,21800,22240,23450,25000])
ob2=ob[1:]-ob[:-1]
ob2

array([ 800,  440, 1210, 1550])

In [130]:
a=np.array([[0,1,2,3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [132]:
a.shape

(2, 4)

In [134]:
a.size

8

In [136]:
a.ndim

2

In [146]:
a[1,3]=15

In [140]:
a[1]

array([10, 11, 12, 13])

In [150]:
a[:,1]

array([ 1, 11])

In [158]:
a=np.array([np.arange(0,6),np.arange(10,16),np.arange(20,26),np.arange(30,36),np.arange(40,46),np.arange(50,56)])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [160]:
a[0,3:5]

array([3, 4])

In [166]:
a[-2:,-2:]

array([[44, 45],
       [54, 55]])

In [164]:
a[:,3]

array([ 3, 13, 23, 33, 43, 53])

In [170]:
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [172]:
a=np.array([0,1,2,3,4])
b=a[2:4]
print(b)

[2 3]


In [174]:
b[0]=10
a

array([ 0,  1, 10,  3,  4])

In [176]:
a=[1,2,3,4,5]
b=a[2:4]
b[0]=10
print(a)

[1, 2, 3, 4, 5]


In [180]:
a=np.array([0,1,2,3,4])
b=a[2:4].copy()
b[0]=10
print(a)

[0 1 2 3 4]


In [5]:
import numpy as np
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [7]:
index=[1,2,-3]
y=a[index]
print(y)

[10 20 70]


In [9]:
mask=np.array([0,1,1,0,0,1,1,1,0,1],dtype=bool)
mask

array([False,  True,  True, False, False,  True,  True,  True, False,
        True])

In [11]:
a[mask]

array([10, 20, 50, 60, 70, 90])

In [13]:
a=np.array([np.arange(0,6),np.arange(10,16),np.arange(20,26),np.arange(30,36),np.arange(40,46),np.arange(50,56)])
a[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [15]:
a[3:,[0,2,4]]

array([[30, 32, 34],
       [40, 42, 44],
       [50, 52, 54]])

In [19]:
mask=np.array([1,0,1,0,1,0],dtype=bool)
a[mask,2]

array([ 2, 22, 42])

In [21]:
y=a[:3]
y

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [25]:
con=np.array([0,0,1,1,0,1],dtype=bool)
a[con]

array([[20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [50, 51, 52, 53, 54, 55]])

In [27]:
a=np.array([0,12,5,20])
a>10

array([False,  True, False,  True])

In [29]:
np.where(a>10)

(array([1, 3], dtype=int64),)

In [31]:
a[a>10]

array([12, 20])

In [33]:
a[np.where(a>10)]

array([12, 20])

In [37]:
a=np.array([1.5,-3],dtype=float)
a

array([ 1.5, -3. ])

In [39]:
a=np.array([1,2,3])
np.asarray(a,dtype=float)

array([1., 2., 3.])

In [41]:
a=np.array([1,2,3])
a.astype(float)

array([1., 2., 3.])

In [43]:
a

array([1, 2, 3])

In [45]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [47]:
a.shape=2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
a.shape

(2, 3)

In [53]:
a=np.arange(6)
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
a

array([0, 1, 2, 3, 4, 5])

In [57]:
a=a.reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [61]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [81]:
x=np.array([[0,1,2],[10,11,12]])
y=np.array([[1,2,3],[12,11,2]])
z=np.concatenate((x,y),axis=0)
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [ 1,  2,  3],
       [12, 11,  2]])

In [83]:
z=np.concatenate((x,y),axis=1)
z

array([[ 0,  1,  2,  1,  2,  3],
       [10, 11, 12, 12, 11,  2]])

In [89]:
z=np.array((x,y))
z

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [12, 11,  2]]])

In [91]:
np.vstack((x,y))

array([[ 0,  1,  2],
       [10, 11, 12],
       [ 1,  2,  3],
       [12, 11,  2]])

In [93]:
np.hstack((x,y))

array([[ 0,  1,  2,  1,  2,  3],
       [10, 11, 12, 12, 11,  2]])

In [95]:
np.dstack((x,y))

array([[[ 0,  1],
        [ 1,  2],
        [ 2,  3]],

       [[10, 12],
        [11, 11],
        [12,  2]]])

In [97]:
a=np.array([-1,2,3,-2])
np.abs(a)

array([1, 2, 3, 2])

In [99]:
np.exp(a)

array([ 0.36787944,  7.3890561 , 20.08553692,  0.13533528])

In [101]:
np.median(a)

0.5

In [103]:
np.cumsum(a)

array([-1,  1,  4,  2])